export const TOGGLE_BEER_DESCRIPTION = 'TOGGLE_BEER_DESCRIPTION'
export const FETCH_BEER_LIST = 'FETCH_BEER_LIST'
export const FETCH_BEER_LIST_SUCCESS = 'FETCH_BEER_LIST_SUCCESS'
export const FETCH_BEER_LIST_FAIL = 'FETCH_BEER_LIST_FAIL'
